# Generated by Django 3.0 on 2019-12-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(default='', max_length=255)),
                ('image', models.FileField(upload_to='images/album/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='', max_length=255)),
                ('image', models.FileField(upload_to='images/genre/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('artist', models.CharField(default='', max_length=255)),
                ('minutes', models.CharField(default='0:00', max_length=255)),
                ('song', models.FileField(upload_to='songs/')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.Genre'),
        ),
    ]
