# Generated by Django 3.0 on 2019-12-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(default='', max_length=255),
        ),
    ]
