# Generated by Django 3.0 on 2019-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20191212_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='deskripsi',
            field=models.TextField(default=''),
        ),
    ]
